
AllCops:
  Excludes:
    - tmp/*

LineLength:
  Max: 100

MethodLength:
  Max: 20

WordArray:
  Enabled: false

# TODO
Documentation:
  Enabled: false

# Currently IndentationWidth reports false positive offence around here document.
IndentationWidth:
  Enabled: false
