language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby
env:
  - RSPEC_VERSION=2.14
  - RSPEC_VERSION=2.99
  - RSPEC_VERSION=3.0
  - RSPEC_VERSION=3.1
before_install: gem update --remote bundler
script: bundle exec rake ci
sudo: false
cache: bundler
